@LinkedIn_Relationship_Manager_HostAddress = https://localhost:7064

GET {{LinkedIn_Relationship_Manager_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{LinkedIn_Relationship_Manager_HostAddress}}/weatherforecast

###

GET {{LinkedIn_Relationship_Manager_HostAddress}}/weatherforecast

###
